const IMG = {
  mecca: "https://images.unsplash.com/photo-1591604129939-f1efa4f849f1?w=800&q=80",
  medina: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=800&q=80",
  dubai: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
  dhaka: "https://images.unsplash.com/photo-1583391733956-3750e0ff4ee8?w=800&q=80",
  coxs: "https://images.unsplash.com/photo-1559120680-6a0f4941f3c9?w=800&q=80",
  luxury: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
  room: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
  pool: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
};

export const HOTELS_SEED = [
  {
    slug: "h1", name: "Fairmont Makkah Clock Royal Tower", city: "Mecca", country: "Saudi Arabia",
    stars: 5, reviewScore: 9.2, reviewCount: 4821, distance: "50m from Masjid al-Haram", distanceKm: 0.05,
    images: [IMG.mecca, IMG.luxury, IMG.room, IMG.pool],
    description: "Iconic luxury hotel in the Abraj Al-Bait complex with direct views of the Holy Kaaba.",
    propertyType: "hotel", amenities: ["wifi", "breakfast", "restaurant", "spa", "gym", "haram_view", "shuttle", "room_service", "ac"],
    freeCancellation: true, breakfastIncluded: true, payAtHotel: false,
    dealLabel: "Sarah Deal", dealDiscount: 16, urgency: "Only 2 rooms left at this price", recommended: true,
    checkInTime: "16:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 48 hours before check-in",
    lat: 21.4225, lng: 39.8262, area: "Abraj Al-Bait, Mecca",
    rooms: [
      { roomCode: "std", name: "Deluxe Haram View Room", pricePerNight: 28500, originalPrice: 34000, description: "King bed, Kaaba view, breakfast included", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: false, roomsLeft: 2 },
      { roomCode: "dlx", name: "Fairmont Gold Suite", pricePerNight: 42000, description: "Separate living area, panoramic Haram view", beds: "1 King + Sofa", maxGuests: 3, breakfast: true, freeCancellation: true, payAtHotel: false, roomsLeft: 1 },
      { roomCode: "ste", name: "Royal Clock Tower Suite", pricePerNight: 85000, description: "Full suite with private prayer area", beds: "2 King", maxGuests: 4, breakfast: true, freeCancellation: false, payAtHotel: false },
    ],
    reviews: [
      { author: "Abdul R.", country: "Bangladesh", reviewDate: "Mar 2026", score: 9.5, title: "Unforgettable Haram view", comment: "Woke up to the Kaaba every morning." },
      { author: "Fatima K.", country: "UK", reviewDate: "Feb 2026", score: 9.0, title: "Premium service", comment: "Staff spoke Bengali! Helped with Zamzam water." },
    ],
  },
  {
    slug: "h2", name: "Dar Al Eiman Royal Hotel", city: "Mecca", country: "Saudi Arabia",
    stars: 4, reviewScore: 8.7, reviewCount: 2103, distance: "150m from Masjid al-Haram", distanceKm: 0.15,
    images: [IMG.mecca, IMG.room, IMG.luxury],
    description: "Premium 4-star hotel near the Haram courtyard with excellent dining.",
    propertyType: "hotel", amenities: ["wifi", "breakfast", "restaurant", "shuttle", "ac", "room_service"],
    freeCancellation: true, breakfastIncluded: true, payAtHotel: true, dealLabel: "Member Price", dealDiscount: 17,
    checkInTime: "15:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 24 hours before check-in",
    lat: 21.4210, lng: 39.8255, area: "Ajyad, Mecca",
    rooms: [
      { roomCode: "std", name: "Standard Twin Room", pricePerNight: 14500, originalPrice: 17500, description: "2 single beds, city view", beds: "2 Single", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: true },
      { roomCode: "dlx", name: "Deluxe Triple Room", pricePerNight: 19800, description: "3 beds, ideal for families", beds: "3 Single", maxGuests: 3, breakfast: true, freeCancellation: true, payAtHotel: true, roomsLeft: 4 },
    ],
    reviews: [{ author: "Rahim M.", country: "Bangladesh", reviewDate: "Jan 2026", score: 8.5, title: "Great for groups", comment: "Booked 8 rooms for our jamaat." }],
  },
  {
    slug: "h3", name: "Madinah Hilton Hotel", city: "Medina", country: "Saudi Arabia",
    stars: 5, reviewScore: 9.0, reviewCount: 3567, distance: "100m from Prophet's Mosque", distanceKm: 0.1,
    images: [IMG.medina, IMG.luxury, IMG.room],
    description: "Luxury rooms at the entrance of Al-Masjid an-Nabawi.",
    propertyType: "hotel", amenities: ["wifi", "breakfast", "restaurant", "spa", "gym", "shuttle", "room_service", "ac"],
    freeCancellation: true, breakfastIncluded: true, payAtHotel: false, dealLabel: "Flash Sale", dealDiscount: 15, recommended: true,
    checkInTime: "15:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 72 hours before check-in",
    lat: 24.4672, lng: 39.6111, area: "Central Medina",
    rooms: [
      { roomCode: "std", name: "Superior Double Room", pricePerNight: 22000, originalPrice: 26000, description: "Queen bed, partial mosque view", beds: "1 Queen", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: false },
      { roomCode: "dlx", name: "Executive Mosque View", pricePerNight: 35000, description: "Direct view of Green Dome", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: false, roomsLeft: 3 },
    ],
    reviews: [{ author: "Sadia A.", country: "Bangladesh", reviewDate: "Feb 2026", score: 9.2, title: "Steps from the Mosque", comment: "Could hear the adhan from our room." }],
  },
  {
    slug: "h4", name: "Al Majeedi AR Riyadh", city: "Medina", country: "Saudi Arabia",
    stars: 3, reviewScore: 7.8, reviewCount: 892, distance: "200m from Prophet's Mosque", distanceKm: 0.2,
    images: [IMG.medina, IMG.room],
    description: "Comfortable budget-friendly hotel perfect for Umrah groups.",
    propertyType: "hotel", amenities: ["wifi", "breakfast", "ac", "shuttle"],
    freeCancellation: false, breakfastIncluded: true, payAtHotel: true,
    checkInTime: "14:00", checkOutTime: "12:00", cancellationPolicy: "Non-refundable rate",
    lat: 24.4660, lng: 39.6100, area: "Markaziyah, Medina",
    rooms: [
      { roomCode: "std", name: "Standard Room", pricePerNight: 8500, description: "2 single beds", beds: "2 Single", maxGuests: 2, breakfast: true, freeCancellation: false, payAtHotel: true },
      { roomCode: "quad", name: "Quad Room", pricePerNight: 12000, description: "4 beds for group pilgrims", beds: "4 Single", maxGuests: 4, breakfast: true, freeCancellation: false, payAtHotel: true, roomsLeft: 6 },
    ],
    reviews: [{ author: "Karim H.", country: "Bangladesh", reviewDate: "Dec 2025", score: 7.5, title: "Good value", comment: "Basic but clean. Walking distance to the mosque." }],
  },
  {
    slug: "h5", name: "Burj Al Arab Jumeirah", city: "Dubai", country: "UAE",
    stars: 5, reviewScore: 9.6, reviewCount: 6234, distance: "Jumeirah Beach", distanceKm: 0.5,
    images: [IMG.dubai, IMG.luxury, IMG.pool, IMG.room],
    description: "The world's most luxurious hotel with butler service and private beach.",
    propertyType: "resort", amenities: ["wifi", "pool", "spa", "gym", "restaurant", "room_service", "parking", "ac"],
    freeCancellation: true, breakfastIncluded: true, payAtHotel: false, dealLabel: "Luxury Deal", dealDiscount: 17, urgency: "High demand — book now",
    checkInTime: "15:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 7 days before check-in",
    lat: 25.1412, lng: 55.1852, area: "Jumeirah, Dubai",
    rooms: [
      { roomCode: "std", name: "Deluxe Suite", pricePerNight: 125000, originalPrice: 150000, description: "2-level suite, sea view", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: false, roomsLeft: 1 },
      { roomCode: "ste", name: "Royal Suite", pricePerNight: 280000, description: "Full floor suite with cinema", beds: "2 King", maxGuests: 4, breakfast: true, freeCancellation: true, payAtHotel: false },
    ],
    reviews: [{ author: "Ahmed S.", country: "UAE", reviewDate: "Mar 2026", score: 9.8, title: "Once in a lifetime", comment: "The gold-plated interiors are unmatched." }],
  },
  {
    slug: "h6", name: "Pan Pacific Sonargaon", city: "Dhaka", country: "Bangladesh",
    stars: 5, reviewScore: 8.9, reviewCount: 1842, distance: "Kawran Bazar, Central Dhaka", distanceKm: 1.2,
    images: [IMG.dhaka, IMG.luxury, IMG.pool, IMG.room],
    description: "Dhaka's premier 5-star business hotel with rooftop pool.",
    propertyType: "hotel", amenities: ["wifi", "pool", "gym", "spa", "restaurant", "parking", "room_service", "ac"],
    freeCancellation: true, breakfastIncluded: false, payAtHotel: true, dealLabel: "Sarah Deal", dealDiscount: 17, recommended: true,
    checkInTime: "14:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 24 hours before check-in",
    lat: 23.7508, lng: 90.3934, area: "Kawran Bazar, Dhaka",
    rooms: [
      { roomCode: "std", name: "Superior Room", pricePerNight: 12500, originalPrice: 15000, description: "King bed, city view", beds: "1 King", maxGuests: 2, breakfast: false, freeCancellation: true, payAtHotel: true },
      { roomCode: "dlx", name: "Club Room", pricePerNight: 18500, description: "Club lounge access", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: true, roomsLeft: 5 },
    ],
    reviews: [{ author: "Nusrat I.", country: "Bangladesh", reviewDate: "Mar 2026", score: 9.0, title: "Best in Dhaka", comment: "Rooftop pool is amazing." }],
  },
  {
    slug: "h7", name: "Hotel GEC Agrabad", city: "Dhaka", country: "Bangladesh",
    stars: 4, reviewScore: 8.2, reviewCount: 567, distance: "GEC Circle, Agrabad", distanceKm: 0.3,
    images: [IMG.dhaka, IMG.room],
    description: "Popular business hotel in the commercial hub.",
    propertyType: "hotel", amenities: ["wifi", "restaurant", "parking", "ac", "shuttle"],
    freeCancellation: true, breakfastIncluded: true, payAtHotel: true,
    checkInTime: "13:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 12 hours before check-in",
    lat: 22.3569, lng: 91.7832, area: "Agrabad, Chittagong",
    rooms: [
      { roomCode: "std", name: "Standard Double", pricePerNight: 6500, description: "Queen bed, work desk", beds: "1 Queen", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: true },
      { roomCode: "dlx", name: "Executive Room", pricePerNight: 9500, description: "King bed, lounge access", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: true },
    ],
    reviews: [{ author: "Tanvir R.", country: "Bangladesh", reviewDate: "Feb 2026", score: 8.0, title: "Solid business hotel", comment: "Good location for meetings." }],
  },
  {
    slug: "h8", name: "Sayeman Beach Resort", city: "Cox's Bazar", country: "Bangladesh",
    stars: 4, reviewScore: 8.5, reviewCount: 1234, distance: "Beachfront, Marine Drive", distanceKm: 0.02,
    images: [IMG.coxs, IMG.pool, IMG.room, IMG.luxury],
    description: "Beachfront resort with infinity pool overlooking the Bay of Bengal.",
    propertyType: "resort", amenities: ["wifi", "pool", "restaurant", "parking", "ac", "spa"],
    freeCancellation: true, breakfastIncluded: true, payAtHotel: true, dealLabel: "Weekend Deal", dealDiscount: 18, urgency: "12 people booked today", recommended: true,
    checkInTime: "14:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 48 hours before check-in",
    lat: 21.4272, lng: 92.0058, area: "Marine Drive, Cox's Bazar",
    rooms: [
      { roomCode: "std", name: "Ocean View Room", pricePerNight: 9800, originalPrice: 12000, description: "Balcony with sea view", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: true },
      { roomCode: "fam", name: "Family Suite", pricePerNight: 16500, description: "2 bedrooms, sea view", beds: "1 King + 2 Single", maxGuests: 4, breakfast: true, freeCancellation: true, payAtHotel: true, roomsLeft: 2 },
    ],
    reviews: [{ author: "Priya D.", country: "Bangladesh", reviewDate: "Mar 2026", score: 8.8, title: "Stunning beach views", comment: "Kids loved the pool." }],
  },
  {
    slug: "h9", name: "Atlantis The Palm", city: "Dubai", country: "UAE",
    stars: 5, reviewScore: 9.1, reviewCount: 8901, distance: "Palm Jumeirah", distanceKm: 2.0,
    images: [IMG.dubai, IMG.pool, IMG.luxury, IMG.room],
    description: "Iconic resort on Palm Jumeirah with Aquaventure Waterpark access.",
    propertyType: "resort", amenities: ["wifi", "pool", "spa", "gym", "restaurant", "parking", "room_service", "ac"],
    freeCancellation: true, breakfastIncluded: false, payAtHotel: false, dealLabel: "Sarah Deal", dealDiscount: 18,
    checkInTime: "15:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 5 days before check-in",
    lat: 25.1304, lng: 55.1177, area: "Palm Jumeirah, Dubai",
    rooms: [
      { roomCode: "std", name: "Ocean King Room", pricePerNight: 45000, originalPrice: 55000, description: "Palm view, waterpark access", beds: "1 King", maxGuests: 2, breakfast: false, freeCancellation: true, payAtHotel: false },
      { roomCode: "dlx", name: "Underwater Suite", pricePerNight: 180000, description: "Floor-to-ceiling aquarium views", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: false, roomsLeft: 1 },
    ],
    reviews: [{ author: "James L.", country: "UK", reviewDate: "Feb 2026", score: 9.3, title: "Kids paradise", comment: "Waterpark alone is worth it." }],
  },
  {
    slug: "h10", name: "Swissôtel Al Maqam", city: "Mecca", country: "Saudi Arabia",
    stars: 5, reviewScore: 8.8, reviewCount: 1567, distance: "80m from Masjid al-Haram", distanceKm: 0.08,
    images: [IMG.mecca, IMG.luxury, IMG.room],
    description: "Swiss hospitality in the heart of Mecca with direct Haram access.",
    propertyType: "hotel", amenities: ["wifi", "breakfast", "restaurant", "gym", "haram_view", "shuttle", "ac", "room_service"],
    freeCancellation: true, breakfastIncluded: true, payAtHotel: false, dealLabel: "Early Bird", dealDiscount: 15,
    checkInTime: "16:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 48 hours before check-in",
    lat: 21.4220, lng: 39.8260, area: "Abraj Al-Bait, Mecca",
    rooms: [
      { roomCode: "std", name: "Superior Room", pricePerNight: 19500, originalPrice: 23000, description: "Partial Haram view", beds: "2 Single", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: false },
      { roomCode: "dlx", name: "Kaaba View Room", pricePerNight: 32000, description: "Direct Kaaba view", beds: "1 King", maxGuests: 2, breakfast: true, freeCancellation: true, payAtHotel: false, roomsLeft: 3 },
    ],
    reviews: [{ author: "Imran B.", country: "Bangladesh", reviewDate: "Jan 2026", score: 8.9, title: "Swiss quality in Mecca", comment: "Impeccable cleanliness and service." }],
  },
];

export const HOTEL_DESTINATIONS = [
  { id: "mecca", name: "Mecca", country: "Saudi Arabia", icon: "🕌" },
  { id: "medina", name: "Medina", country: "Saudi Arabia", icon: "🕌" },
  { id: "dhaka", name: "Dhaka", country: "Bangladesh", icon: "🏙️" },
  { id: "dubai", name: "Dubai", country: "UAE", icon: "🏗️" },
  { id: "coxs-bazar", name: "Cox's Bazar", country: "Bangladesh", icon: "🏖️" },
];
