export const TOURS_SEED = [
  {
    slug: "t1", title: "Cox's Bazar Beach Getaway", destination: "Cox's Bazar",
    durationLabel: "3 Days / 2 Nights", durationDays: 3, price: 14500,
    highlight: "Sunset beach walk, Himchori waterfall, Inani coral beach",
    description: "Enjoy the world's longest natural sandy beach in Cox's Bazar.",
    inclusions: ["Premium resort accommodation (2 nights)", "Daily buffet breakfast", "AC private car", "Himchori & Inani sightseeing", "Local guide"],
    exclusions: ["Lunch & dinner", "Personal shopping", "Water sports"],
    itinerary: [
      { day: 1, title: "Arrival & Beach Sunset", desc: "Airport pick up. Check-in. Sunset at Laboni beach." },
      { day: 2, title: "Marine Drive Tour", desc: "Himchori national park and Inani coral sands." },
      { day: 3, title: "Departure", desc: "Burmese market visit. Airport transfer." },
    ],
    imageUrl: "https://images.unsplash.com/photo-1559120680-6a0f4941f3c9?w=800&q=80",
    source: "Local Direct",
  },
  {
    slug: "t2", title: "Sundarbans Mangrove Cruise", destination: "Sundarbans",
    durationLabel: "4 Days / 3 Nights", durationDays: 4, price: 19800,
    highlight: "Tiger spotting trail, forest boat cruise, wildlife sanctuary",
    description: "Adventurous deep forest river boat cruise in the largest mangrove forest.",
    inclusions: ["Cruise boat cabins (3 nights)", "All meals", "Forest permits", "Armed guard", "Canal tour"],
    exclusions: ["Personal tips", "Soft drinks"],
    itinerary: [
      { day: 1, title: "Khulna Boarding", desc: "Board cruise vessel toward Sundarbans." },
      { day: 2, title: "Kotka Wildlife", desc: "Deer sanctuary and canal cruising." },
      { day: 3, title: "Harbaria Trail", desc: "Tiger tracks and dolphin spotting." },
      { day: 4, title: "Return", desc: "Sail back to Khulna." },
    ],
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    source: "Local Direct",
  },
  {
    slug: "t3", title: "Sylhet Tea Gardens Retreat", destination: "Sylhet",
    durationLabel: "3 Days / 2 Nights", durationDays: 3, price: 11000,
    highlight: "Jaflong stone collection, tea garden trail, Lalakhal boat ride",
    description: "Relax amidst tea estates in Sreemangal and Sylhet.",
    inclusions: ["Cottage room (2 nights)", "Breakfast", "Lalakhal cruise", "AC transport"],
    exclusions: ["Personal shopping", "Special meals"],
    itinerary: [
      { day: 1, title: "Jaflong", desc: "Explore Jaflong stone river." },
      { day: 2, title: "Lalakhal", desc: "Swamp forest and emerald waters." },
      { day: 3, title: "Tea Gardens", desc: "Sreemangal estates and departure." },
    ],
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    source: "Local Direct",
  },
  {
    slug: "t4", title: "Maldives Island Holiday Special", destination: "Maldives",
    durationLabel: "5 Days / 4 Nights", durationDays: 5, price: 68000,
    highlight: "Overwater bungalow, speed boat transfers, snorkeling gear",
    description: "Dream tropical beach vacation in Maldives.",
    inclusions: ["Ocean resort (4 nights)", "Half-board meals", "Speed boat transfers", "Snorkeling gear"],
    exclusions: ["International flights", "Premium bar"],
    itinerary: [
      { day: 1, title: "Arrival", desc: "Speedboat to island villa." },
      { day: 2, title: "Snorkeling", desc: "Coral reef safari." },
      { day: 3, title: "Island Hopping", desc: "Fishing cruise." },
      { day: 4, title: "Leisure", desc: "Beach relaxation day." },
      { day: 5, title: "Departure", desc: "Return to airport." },
    ],
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    source: "Viator API",
  },
];
